namespace Bojan.Application.Common;

/// <summary>
/// Commits work, and runs a block of it atomically.
/// </summary>
/// <remarks>
/// The transaction port exists for exactly one caller that cannot do without
/// it: order placement re-prices, re-checks stock, reserves it and records a
/// coupon redemption, and a partial application of that is the worst failure
/// mode the system has (<c>BACKEND.md</c> Phase 4). Everything else saves
/// normally.
/// </remarks>
public interface IUnitOfWork
{
    Task SaveChangesAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Runs <paramref name="operation"/> inside a database transaction,
    /// committing if it returns and rolling back if it throws. Nested calls
    /// join the outer transaction rather than opening a second one.
    /// </summary>
    Task<T> ExecuteInTransactionAsync<T>(Func<CancellationToken, Task<T>> operation, CancellationToken cancellationToken);
}

/// <summary>Who is making this request, resolved from the credential rather than from anything in the body.</summary>
public interface ICurrentUser
{
    /// <summary>The signed-in customer, or null on a public endpoint.</summary>
    Guid? CustomerId { get; }

    /// <summary>The signed-in operator, or null outside the panel's endpoints.</summary>
    Guid? AdminId { get; }

    /// <summary>Operator's role, lowercase as the panel writes it — <c>owner</c>, <c>product</c>, <c>sales</c>, <c>support</c>.</summary>
    string? AdminRole { get; }

    /// <summary>Caller address, for the audit trail. Null when it cannot be determined.</summary>
    string? Ip { get; }
}

/// <summary>
/// Records an operator action.
/// </summary>
/// <remarks>
/// <c>BACKEND.md</c> Phase 7: "Every write here goes in an audit log." The
/// implementation adds the row to the same change tracker as the write it
/// describes, so one <see cref="IUnitOfWork.SaveChangesAsync"/> commits both
/// or neither.
/// </remarks>
public interface IAuditLog
{
    void Record(string action, string target);
}

/// <summary>
/// Somewhere to put an uploaded file.
/// </summary>
/// <remarks>
/// <c>BACKEND.md</c> Phase 8: "Uploads are one shared decision, not six." This
/// is that decision, made once: through-the-API rather than direct-to-storage
/// with a signed URL. Product images, avatars, return photos and B2B
/// attachments all come through here, so swapping local disk for S3-compatible
/// object storage later is one implementation, not six call-site changes.
/// </remarks>
public interface IFileStorage
{
    /// <summary>Stores the stream and returns the URL the frontend should render.</summary>
    Task<string> SaveAsync(
        string folder,
        string fileName,
        string contentType,
        Stream content,
        CancellationToken cancellationToken);

    Task DeleteAsync(string url, CancellationToken cancellationToken);

    /// <summary>
    /// Whether <paramref name="url"/> is one this storage issued, in
    /// <paramref name="folder"/>.
    /// </summary>
    /// <remarks>
    /// Anywhere a caller hands back a URL to be stored on a record, this is the
    /// check that keeps the field from becoming "any URL the client likes".
    /// Without it a profile picture could point at another site — a tracking
    /// pixel that fires for every operator who opens the customer, or a
    /// <c>data:</c> payload — none of which is a file this system ever
    /// accepted, sniffed or stored.
    /// </remarks>
    bool IsOwnUrl(string url, string folder);
}

/// <summary>
/// Somewhere to put a server-generated file — a backup archive, not a user
/// upload.
/// </summary>
/// <remarks>
/// <para>
/// Deliberately not <see cref="IFileStorage"/>: that port only accepts the
/// four image types it sniffs by magic bytes, because it exists to hold what
/// a browser hands it. A backup archive is generated by this API itself, for
/// an operator who is already authenticated to the route that triggers it —
/// the threat model an upload needs (a stranger's arbitrary bytes) does not
/// apply here, and forcing this content through the image allow-list would
/// only reject it.
/// </para>
/// <para>
/// Just as deliberately, this port never hands back a URL — a backup archive
/// is exactly the kind of thing <see cref="IFileStorage.SaveAsync"/>'s public,
/// unauthenticated base URL must never serve. <see cref="SaveAsync"/> returns
/// an opaque reference private to this port, and <see cref="OpenReadAsync"/>
/// is the only way back to the bytes — which the download route reads and
/// streams itself, behind the same authorisation the rest of screen 156 sits
/// behind, rather than redirecting the browser to a link anyone holding it
/// could open.
/// </para>
/// </remarks>
public interface IBackupArchiver
{
    /// <summary>Stores the bytes and returns a reference private to this port — never a public URL.</summary>
    Task<string> SaveAsync(string fileName, byte[] content, CancellationToken cancellationToken);

    /// <summary>
    /// Opens a destination to write into, for content too large to hold.
    /// </summary>
    /// <remarks>
    /// A report export is a few hundred kilobytes and passing a byte array is
    /// fine. A database dump is not: buffering one in memory to hand it over is
    /// how a backup takes the API down on the day it is most needed. The
    /// reference is settled before anything is written, so the caller can
    /// record it and stream into the stream it gets back.
    /// </remarks>
    Task<(string Reference, Stream Destination)> OpenWriteAsync(string fileName, CancellationToken cancellationToken);

    /// <summary>Reads back what <see cref="SaveAsync"/> stored, by the reference it returned.</summary>
    Task<byte[]?> OpenReadAsync(string reference, CancellationToken cancellationToken);

    /// <summary>
    /// The same content as a stream, for a download that must not be buffered.
    /// </summary>
    Task<Stream?> OpenReadStreamAsync(string reference, CancellationToken cancellationToken);

    /// <summary>Removes an archive — used to clean up after a backup that failed part-written.</summary>
    Task DeleteAsync(string reference, CancellationToken cancellationToken);
}

/// <summary>
/// Produces a restorable dump of the database this API is connected to.
/// </summary>
/// <remarks>
/// <para>
/// Behind a port because what performs the dump is a property of the database,
/// not of this application: for PostgreSQL it is <c>pg_dump</c>, and the
/// implementation shells out to it with the credentials from the connection
/// string this process is already using. Nothing in the application layer
/// should know that.
/// </para>
/// <para>
/// The one thing it must never do is succeed quietly. A backup that reports
/// "completed" over an empty file is worse than having no backup feature at
/// all: it is the difference between knowing you are unprotected and finding
/// out at a restore.
/// </para>
/// </remarks>
public interface IDatabaseDumper
{
    /// <summary>True when the tooling this needs is actually present.</summary>
    Task<bool> IsAvailableAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Writes a restorable dump into <paramref name="destination"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// The dump could not be produced. The message is what the operator sees on
    /// screen 156 beside a job marked failed.
    /// </exception>
    Task DumpAsync(Stream destination, CancellationToken cancellationToken);
}

/// <summary>The gateway's answer to "start a payment".</summary>
public sealed record PaymentSession(string PaymentUrl, string Reference);

/// <summary>
/// Starts and verifies a payment.
/// </summary>
/// <remarks>
/// Behind a port so the money path does not depend on which Iranian PSP is
/// wired up. Which one that is, is a stored setting rather than a registration
/// — the owner chooses it in the panel — so every method here re-reads it, and
/// the answer can change between two calls without a restart.
/// </remarks>
public interface IPaymentGateway
{
    /// <summary>
    /// Asks for somewhere to send the shopper to pay.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// No provider is configured, or the one that is refused the request. The
    /// callers treat this as "the order exists, the redirect does not", which
    /// is a different outcome from a declined payment and has to stay that way.
    /// </exception>
    Task<PaymentSession> StartAsync(string orderNumber, long amountToman, CancellationToken cancellationToken);

    /// <summary>
    /// True when the gateway confirms the reference was actually paid.
    /// </summary>
    /// <param name="orderNumber">
    /// The same value <see cref="StartAsync"/> was given. Carried because not
    /// every provider identifies a payment by its own reference alone — IDPay
    /// verifies on the pair, and rejects a request that names only one of them.
    /// </param>
    /// <remarks>
    /// False means the bank said no. It throws rather than returning false when
    /// nobody could be asked, because "unknown" written to an order as "not
    /// paid" is how a settled payment gets lost.
    /// </remarks>
    Task<bool> VerifyAsync(
        string reference,
        string orderNumber,
        long amountToman,
        CancellationToken cancellationToken);

    /// <summary>
    /// True when a bank is actually in the loop.
    /// </summary>
    /// <remarks>
    /// False for the stub that approves everything and for a shop with no
    /// gateway chosen yet. Order placement can afford to not check it — an
    /// order taken against a stub is still an unpaid debt against real goods,
    /// caught the same way a declined one would be. Wallet top-up cannot:
    /// a verification nobody asked a bank would let it mint spendable balance
    /// out of nothing, so <c>AccountService.StartGatewayTopUpAsync</c> refuses
    /// outright unless this is true.
    /// </remarks>
    Task<bool> TakesRealMoneyAsync(CancellationToken cancellationToken);
}

/// <summary>
/// Delivers a notification on whichever channel it was composed for.
/// </summary>
/// <remarks>
/// In-app notifications are rows this API owns; email, SMS and push leave the
/// system. Keeping all four behind one port means the composer screen's write
/// does not branch on channel.
/// </remarks>
public interface INotificationDispatcher
{
    Task DispatchAsync(Guid notificationCampaignId, CancellationToken cancellationToken);
}

/// <summary>
/// The storefront's one question about the shop's own operating state, asked
/// without a credential.
/// </summary>
/// <remarks>
/// The panel's "حالت تعمیر و نگهداری" switch writes through the generic
/// settings row the rest of that screen uses — <c>{ section: "store", key:
/// "maintenance" }</c>, because the switch lives on the store settings screen
/// (<c>apps/admin/src/app/settings/page.tsx</c>, which posts
/// <c>section="store"</c>). This port is the read side a visitor can reach
/// without a credential: the storefront checks it on every request so the
/// switch actually gates the site, instead of a value only ever admins see.
/// </remarks>
public interface IStoreStatusQueries
{
    Task<bool> IsMaintenanceModeEnabledAsync(CancellationToken cancellationToken);
}
